### ISSUE TITLE
Splashing window when open tagged file

### ISSUE THREAD

**Issue by tuyenpm9** [soramugi/auto-ctags.vim#10]
auto-ctags seems to everytime I trigger a save `:w` and a cmd window open and destroyed immediately right after that. I think this should be fixed, pretty annoying and I have to disabled plugin entirely.  
I can sure because it happened only on files that I ran `ctags -R .` on its parent folders.

Gvim 8/windows 10/universal ctags

**Comment by soramugi** [comment]
Windows was not supported.
But now it is supported
https://github.com/soramugi/auto-ctags.vim/pull/15
