### ISSUE TITLE
Restrict tags to specific filetypes

### ISSUE THREAD

**Issue by mredolatti-devspark** [soramugi/auto-ctags.vim#8]
Hi,

I'm finding this plugin really useful, but is there any way to restrict tags file creation to certain file-extensions?

Perharps i'm missing some configuration option, but i'm getting tags created for every file I open in vim, whether it's a source file, a random .txt, or an /etc/ configuration file.

Thanks!

**Comment by soramugi** [comment]
It is possible. For example, in the case of PHP is

```~/.vimrc
let g:auto_ctags_tags_args = '--languages=php --tag-relative --recurse --sort=yes'
```

Extension list of the specified PHP will be confirmed in the following

    $ ctags --list-maps | grep php
    PHP      *.php *.php3 *.phtml *.inc

Thanks!
